ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.partyplanner.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/partyplanner"
    url = ${?DATABASE_URL}
    user = "dev"
    user = ${?DATABASE_USER}
    password = "dev"
    password = ${?DATABASE_PASSWORD}
}

jwt {
    secret = "changeme"
    secret = ${?JWT_SECRET}
    issuer = "partyplanner"
    audience = "partyplanner-users"
}